const Discord = require("discord.js")
const fetch = require("node-fetch")

module.exports.run = async (bot, message, args) => {
    const msg = await message.channel.send("Checking out.. please wait")
    if(!message.channel.nsfw) return msg.edit("Cannot display nsfw content in sfw channel")
    
    const body1  = await fetch("https://nekobot.xyz/api/image?type=hentai").then(res => res.json())
    const body2  = await fetch("https://nekobot.xyz/api/image?type=hentai").then(res => res.json())
    const body3  = await fetch("https://nekobot.xyz/api/image?type=hentai").then(res => res.json())
    const body4  = await fetch("https://nekobot.xyz/api/image?type=hentai").then(res => res.json())
    msg.delete()
    const embed1 = new Discord.RichEmbed()
        .setTitle("Click here if the image failed to load")
        .setURL(body1.message)
        .setColor("#000000")
        .setImage(body1.message)
        .setFooter(`Requested by ${message.author.tag}`)
    message.channel.send(embed1)

    const embed2 = new Discord.RichEmbed()
        .setTitle("Click here if the image failed to load")
        .setURL(body2.message)
        .setColor("#000000")
        .setImage(body2.message)
        .setFooter(`Requested by ${message.author.tag}`)
    message.channel.send(embed2)

    const embed3 = new Discord.RichEmbed()
        .setTitle("Click here if the image failed to load")
        .setURL(body3.message)
        .setColor("#000000")
        .setImage(body3.message)
        .setFooter(`Requested by ${message.author.tag}`)
    message.channel.send(embed3)

    const embed4 = new Discord.RichEmbed()
        .setTitle("Click here if the image failed to load")
        .setURL(body4.message)
        .setColor("#000000")
        .setImage(body4.message)
        .setFooter(`Requested by ${message.author.tag}`)
    message.channel.send(embed4)
}